### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by nibytes** [drozhzhin-n-e/ngx-pinch-zoom#1]
Error: ./node_modules/ngx-pinch-zoom/lib/pinch-zoom.directive.ts
Module build failed: Error: ENOENT: no such file or directory, open 'F:\Work\oylaApp\node_modules\ngx-pinch-zoom\lib\pinch-zoom.directive.js'
 @ ./node_modules/ngx-pinch-zoom/components.js 1:29-66
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
    at new BuildError (F:\Work\oylaApp\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at callback (F:\Work\oylaApp\node_modules\@ionic\app-scripts\dist\webpack.js:121:28)
    at emitRecords.err (F:\Work\oylaApp\node_modules\webpack\lib\Compiler.js:269:13)
    at Compiler.emitRecords (F:\Work\oylaApp\node_modules\webpack\lib\Compiler.js:375:38)
    at emitAssets.err (F:\Work\oylaApp\node_modules\webpack\lib\Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (F:\Work\oylaApp\node_modules\webpack\lib\Compiler.js:368:12)
    at next (F:\Work\oylaApp\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.compiler.plugin (F:\Work\oylaApp\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (F:\Work\oylaApp\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit (F:\Work\oylaApp\node_modules\webpack\lib\Compiler.js:365:9)

**Comment by nibytes** [comment]
Copyed your code https://github.com/drozhzhin-n-e/ngx-pinch-zoom/blob/master/src/app/pinch-zoom.directive.ts to my project and all work fine. Very good zoom the best I've seen in Ionic2 packages. Thank you. Lacks double tap, but it's really the best I've seen.

**Comment by gregavola** [comment]
@nibytes how did you solve this?

**Comment by drozhzhin-n-e** [comment]
try version 1.0.2, maybe it will solve the problem

**Comment by kpollocktoo** [comment]
Thanks for replying! 1.0.2 has the js but is missing the js.map file so the build still fails. Im trying to generate the .map file but I'm new to this. if you have it, or can generate it easily I'd appreciate it. That should fix the build. Thanks again

**Comment by drozhzhin-n-e** [comment]
@kpollocktoo please try version 1.0.3

**Comment by kpollocktoo** [comment]
Ok, were moving forward now I get:

ERROR Error: Uncaught (in promise): ReferenceError: __decorate is not defined
ReferenceError: __decorate is not defined
    at Object.689 (pinch-zoom.component.ts:33)

which seems to have to do with the tsconfig.json youre using to compile?

**Comment by kpollocktoo** [comment]
I was looking at this when I suggested the tsconfig.json change
https://stackoverflow.com/questions/36808303/webpackangular2-error-uncaught-referenceerror-decorate-is-not-defined

**Comment by drozhzhin-n-e** [comment]
@kpollocktoo ok, I removed "noEmitHelpers": true from tsconfig.json, v1.0.4

**Comment by kpollocktoo** [comment]
Again, thank you for your help! Im still getting the  __decorate is not defined error - same trace

**Comment by drozhzhin-n-e** [comment]
@kpollocktoo I published a new version, generated by yeoman generator. I checked the library in webpack and found no errors.
